export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const ADMIN_DETAIL_REQUEST = 'ADMIN_DETAIL_REQUEST';
export const ADMIN_DETAIL_SUCCESS = 'ADMIN_DETAIL_SUCCESS';
export const ADMIN_DETAIL_FAIL = 'ADMIN_DETAIL_FAIL';
export const ADMIN_DETAIL_RESET = 'ADMIN_DETAIL_RESET';

export const ADMIN_UPDATE_REQUEST = 'ADMIN_UPDATE_REQUEST';
export const ADMIN_UPDATE_SUCCESS = 'ADMIN_UPDATE_SUCCESS';
export const ADMIN_UPDATE_FAIL = 'ADMIN_UPDATE_FAIL';
export const ADMIN_UPDATE_RESET = 'ADMIN_UPDATE_RESET';